### ISSUE TITLE
Docker Image Location

### ISSUE THREAD

**Issue by tobru** [nginxinc/openshift-nginx#2]
Great to see an official Docker Image of Nginx which runs on OpenShift! Will this image be pushed to Docker Hub? Or is it meant to be built manually by the user?

**Comment by alessfg** [comment]
Hi @tobru! There are ongoing discussions (nginxinc/docker-nginx/pull/188) about whether this image will be pushed to Docker Hub or not, but it will take some time before a final decision is made. For now my recommendation would be to build the Docker image locally and push it to your personal Dockerhub repository.

**Comment by tobru** [comment]
Thanks @alessfg for the information. I then close this issue as this answer my question very well.
